const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
const RECEIVE_TOKEN = "RECEIVE_TOKEN";
const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export default {
    REQUEST_SIGN_IN,
    RECEIVE_TOKEN,
    SIGN_IN_ERROR,
}