const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
const RECEIVE_TOKEN = "RECEIVE_TOKEN";
const SIGN_IN_ERROR = "SIGN_IN_ERROR";
const LOG_OUT = "LOG_OUT"
const RECEIVE_ROLE = "RECEIVE_ROLE"
const RECEIVE_ID = "RECEIVE_ID"
export default {
    REQUEST_SIGN_IN,
    RECEIVE_TOKEN,
    SIGN_IN_ERROR,
    LOG_OUT,
    RECEIVE_ROLE,
    RECEIVE_ID
}