const REQUEST_PRODUCTS = "REQUEST_PRODUCTS"
const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS"
const FILTER_PRODUCTS = "FILTER_PRODUCTS"
const ERROR = "ERROR"

export default {
    REQUEST_PRODUCTS,
    RECEIVE_PRODUCTS,
    FILTER_PRODUCTS,
    ERROR
}