const REQUEST_PRODUCTS = "REQUEST_PRODUCTS"
const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS"
const FILTER_PRODUCTS = "FILTER_PRODUCTS"
const REQUEST_SINGLE = "REQUEST_SINGLE"
const RECEIVE_SINGLE = "RECEIVE_SINGLE"
const ERROR = "ERROR"

export default {
    REQUEST_PRODUCTS,
    RECEIVE_PRODUCTS,
    FILTER_PRODUCTS,
    REQUEST_SINGLE,
    RECEIVE_SINGLE,
    ERROR
}