const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
const RECEIVE_TOKEN = "RECEIVE_TOKEN";
const SIGN_IN_ERROR = "SIGN_IN_ERROR";

const REQUEST_SIGN_UP = "REQUEST_SIGN_UP";
const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export default {
    REQUEST_SIGN_IN,
    RECEIVE_TOKEN,
    SIGN_IN_ERROR,
    REQUEST_SIGN_UP,
    SIGN_UP_SUCCESS,
    SIGN_UP_ERROR,
}